services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hackernewsDB
    volumes:
     - postgres_data:/var/lib/postgresql/data
    networks:
      - hckernews-network
    ports:
     - "5432:5432"
networks:
  hckernews-network:
    driver: bridge
volumes:
  postgres_data:
    driver: local